---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: ansible-role-certbot
      certbot_email: robert@meinit.nl
      certbot_domains:
        - meinit.nl
        - robertdebock.nl
      certbot_ci_mode: true
